"l2_loop:\n\t"
"slti t0, %[N], 2\n\t"
"addi %[others_cnt], %[others_cnt], 2\n\t"
"bnez t0, l2_done\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"srli %[N], %[N], 1\n\t"
"addi %[log], %[log], 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal zero, l2_loop\n\t"
"l2_done:\n\t"
